### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Xnuvers007** [peter279k/github-follower-bot#1]
![Screenshot_20211207_075039](https://user-images.githubusercontent.com/62522733/144946058-1e12bdcf-db13-4f13-a4cf-282fec290673.jpg)

TypeError string Indices must Integers

**Comment by peter279k** [comment]
Thanks for your reply. Do you set your own environment variables?

Please look at [line 11](https://github.com/peter279k/github-follower-bot/blob/master/follower_bot.py#L11) and [line 12](https://github.com/peter279k/github-follower-bot/blob/master/follower_bot.py#L12).

**Comment by Xnuvers007** [comment]
> Thanks for your reply. Do you set your own environment variables?
> 
> Please look at [line 11](https://github.com/peter279k/github-follower-bot/blob/master/follower_bot.py#L11) and [line 12](https://github.com/peter279k/github-follower-bot/blob/master/follower_bot.py#L12).

I use it on termux android

Thank you for reply

**Comment by peter279k** [comment]
I've no experience on Termux Android. And I think you should ensure environment variables are configured correctly.

Maybe you can try to run this Python script without Termux and run on common Bash.

**Comment by peter279k** [comment]
Closed and open another issue if you've another problem :).
